steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/net-recovery-app:latest', '.']
    id: build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/net-recovery-app:latest']
    id: push

images:
  - 'gcr.io/$PROJECT_ID/net-recovery-app:latest'